// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// WARNING! Do not edit this file manually, your changes will be overwritten.

module;

#include "ArgumentsObject.h"

export module GraphQL.Validation.ArgumentsObject;

export namespace graphql::validation::object {

using object::Arguments;

} // namespace graphql::validation::object
