// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// WARNING! Do not edit this file manually, your changes will be overwritten.

module;

#include "MessageObject.h"

export module GraphQL.Validation.MessageObject;

export namespace graphql::validation::object {

using object::Message;

} // namespace graphql::validation::object
