// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// WARNING! Do not edit this file manually, your changes will be overwritten.

module;

#include "MessageObject.h"

export module GraphQL.Validation.MessageObject;

namespace included = graphql::validation::object;

export namespace graphql::validation::object {

namespace exported {

using Message = included::Message;

} // namespace exported

using namespace exported;

} // namespace graphql::validation::object
