// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// WARNING! Do not edit this file manually, your changes will be overwritten.

module;

#include "MutateDogResultObject.h"

export module GraphQL.Validation.MutateDogResultObject;

export namespace graphql::validation::object {

using object::MutateDogResult;

} // namespace graphql::validation::object
