// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// WARNING! Do not edit this file manually, your changes will be overwritten.

module;

#include "CompleteTaskPayloadObject.h"

export module GraphQL.Today.CompleteTaskPayloadObject;

export namespace graphql::today::object {

using object::CompleteTaskPayload;

} // namespace graphql::today::object
