// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// WARNING! Do not edit this file manually, your changes will be overwritten.

module;

#include "TodayFolderConnectionObject.h"

export module GraphQL.Today.FolderConnectionObject;

export namespace graphql::today::object {

using object::FolderConnection;

} // namespace graphql::today::object
