// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// WARNING! Do not edit this file manually, your changes will be overwritten.

module;

#include "TodayPageInfoObject.h"

export module GraphQL.Today.PageInfoObject;

export namespace graphql::today::object {

using object::PageInfo;

} // namespace graphql::today::object
