// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// WARNING! Do not edit this file manually, your changes will be overwritten.

module;

#include "QueryObject.h"

export module GraphQL.Today.QueryObject;

export namespace graphql::today::object {

using object::Query;

} // namespace graphql::today::object
