// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// WARNING! Do not edit this file manually, your changes will be overwritten.

module;

#include "TaskObject.h"

export module GraphQL.Today.TaskObject;

namespace included = graphql::today::object;

export namespace graphql::today::object {

namespace exported {

using included::Task;

} // namespace exported

using namespace exported;

} // namespace graphql::today::object
