// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// WARNING! Do not edit this file manually, your changes will be overwritten.

#include "QueryObject.h"

#include "graphqlservice/internal/Introspection.h"

#include "graphqlservice/introspection/SchemaObject.h"
#include "graphqlservice/introspection/TypeObject.h"

#include <algorithm>
#include <functional>
#include <sstream>
#include <stdexcept>
#include <unordered_map>

using namespace std::literals;

namespace graphql::scalar {
namespace object {

Query::Query(std::unique_ptr<const Concept> pimpl) noexcept
	: service::Object{ getTypeNames(), getResolvers() }
	, _schema { GetSchema() }
	, _pimpl { std::move(pimpl) }
{
}

service::TypeNames Query::getTypeNames() const noexcept
{
	return {
		R"gql(Query)gql"sv
	};
}

service::ResolverMap Query::getResolvers() const noexcept
{
	return {
		{ R"gql(add)gql"sv, [this](service::ResolverParams&& params) { return resolveAdd(std::move(params)); } },
		{ R"gql(echo)gql"sv, [this](service::ResolverParams&& params) { return resolveEcho(std::move(params)); } },
		{ R"gql(maybe)gql"sv, [this](service::ResolverParams&& params) { return resolveMaybe(std::move(params)); } },
		{ R"gql(__type)gql"sv, [this](service::ResolverParams&& params) { return resolve_type(std::move(params)); } },
		{ R"gql(__schema)gql"sv, [this](service::ResolverParams&& params) { return resolve_schema(std::move(params)); } },
		{ R"gql(__typename)gql"sv, [this](service::ResolverParams&& params) { return resolve_typename(std::move(params)); } }
	};
}

void Query::beginSelectionSet(const service::SelectionSetParams& params) const
{
	_pimpl->beginSelectionSet(params);
}

void Query::endSelectionSet(const service::SelectionSetParams& params) const
{
	_pimpl->endSelectionSet(params);
}

service::AwaitableResolver Query::resolveEcho(service::ResolverParams&& params) const
{
	auto argValue = service::ModifiedArgument<bigint::BigInt>::require("value", params.arguments);
	std::unique_lock resolverLock(_resolverMutex);
	service::SelectionSetParams selectionSetParams { static_cast<const service::SelectionSetParams&>(params) };
	auto directives = std::move(params.fieldDirectives);
	auto result = _pimpl->getEcho(service::FieldParams { std::move(selectionSetParams), std::move(directives) }, std::move(argValue));
	resolverLock.unlock();

	return service::ModifiedResult<bigint::BigInt>::convert(std::move(result), std::move(params));
}

service::AwaitableResolver Query::resolveAdd(service::ResolverParams&& params) const
{
	auto argLeft = service::ModifiedArgument<bigint::BigInt>::require("left", params.arguments);
	auto argRight = service::ModifiedArgument<bigint::BigInt>::require("right", params.arguments);
	std::unique_lock resolverLock(_resolverMutex);
	service::SelectionSetParams selectionSetParams { static_cast<const service::SelectionSetParams&>(params) };
	auto directives = std::move(params.fieldDirectives);
	auto result = _pimpl->getAdd(service::FieldParams { std::move(selectionSetParams), std::move(directives) }, std::move(argLeft), std::move(argRight));
	resolverLock.unlock();

	return service::ModifiedResult<bigint::BigInt>::convert(std::move(result), std::move(params));
}

service::AwaitableResolver Query::resolveMaybe(service::ResolverParams&& params) const
{
	auto argValue = service::ModifiedArgument<bigint::BigInt>::require<service::TypeModifier::Nullable>("value", params.arguments);
	std::unique_lock resolverLock(_resolverMutex);
	service::SelectionSetParams selectionSetParams { static_cast<const service::SelectionSetParams&>(params) };
	auto directives = std::move(params.fieldDirectives);
	auto result = _pimpl->getMaybe(service::FieldParams { std::move(selectionSetParams), std::move(directives) }, std::move(argValue));
	resolverLock.unlock();

	return service::ModifiedResult<bigint::BigInt>::convert<service::TypeModifier::Nullable>(std::move(result), std::move(params));
}

service::AwaitableResolver Query::resolve_typename(service::ResolverParams&& params) const
{
	return service::Result<std::string>::convert(std::string{ R"gql(Query)gql" }, std::move(params));
}

service::AwaitableResolver Query::resolve_schema(service::ResolverParams&& params) const
{
	return service::Result<service::Object>::convert(std::static_pointer_cast<service::Object>(std::make_shared<introspection::object::Schema>(std::make_shared<introspection::Schema>(_schema))), std::move(params));
}

service::AwaitableResolver Query::resolve_type(service::ResolverParams&& params) const
{
	auto argName = service::ModifiedArgument<std::string>::require("name", params.arguments);
	const auto& baseType = _schema->LookupType(argName);
	std::shared_ptr<introspection::object::Type> result { baseType ? std::make_shared<introspection::object::Type>(std::make_shared<introspection::Type>(baseType)) : nullptr };

	return service::ModifiedResult<introspection::object::Type>::convert<service::TypeModifier::Nullable>(result, std::move(params));
}

} // namespace object

void AddQueryDetails(const std::shared_ptr<schema::ObjectType>& typeQuery, const std::shared_ptr<schema::Schema>& schema)
{
	typeQuery->AddFields({
		schema::Field::Make(R"gql(echo)gql"sv, R"md(Echo a BigInt argument straight back out, round-tripping through bigint::BigInt.)md"sv, std::nullopt, schema->WrapType(introspection::TypeKind::NON_NULL, schema->LookupType(R"gql(BigInt)gql"sv)), {
			schema::InputValue::Make(R"gql(value)gql"sv, R"md()md"sv, schema->WrapType(introspection::TypeKind::NON_NULL, schema->LookupType(R"gql(BigInt)gql"sv)), R"gql()gql"sv)
		}),
		schema::Field::Make(R"gql(add)gql"sv, R"md(Add two BigInt values together on the C++ side and return the result.)md"sv, std::nullopt, schema->WrapType(introspection::TypeKind::NON_NULL, schema->LookupType(R"gql(BigInt)gql"sv)), {
			schema::InputValue::Make(R"gql(left)gql"sv, R"md()md"sv, schema->WrapType(introspection::TypeKind::NON_NULL, schema->LookupType(R"gql(BigInt)gql"sv)), R"gql()gql"sv),
			schema::InputValue::Make(R"gql(right)gql"sv, R"md()md"sv, schema->WrapType(introspection::TypeKind::NON_NULL, schema->LookupType(R"gql(BigInt)gql"sv)), R"gql()gql"sv)
		}),
		schema::Field::Make(R"gql(maybe)gql"sv, R"md(Return an optional BigInt, or null when no value is provided.)md"sv, std::nullopt, schema->LookupType(R"gql(BigInt)gql"sv), {
			schema::InputValue::Make(R"gql(value)gql"sv, R"md()md"sv, schema->LookupType(R"gql(BigInt)gql"sv), R"gql()gql"sv)
		})
	});
}

} // namespace graphql::scalar
