// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// WARNING! Do not edit this file manually, your changes will be overwritten.

#pragma once

#ifndef COMPLETETASKPAYLOADOBJECT_H
#define COMPLETETASKPAYLOADOBJECT_H

#include "TodaySchema.h"

namespace graphql::today::object {

class CompleteTaskPayload
	: public service::Object
{
protected:
	explicit CompleteTaskPayload();

public:
	virtual service::FieldResult<std::shared_ptr<Task>> getTask(service::FieldParams&& params) const;
	virtual service::FieldResult<std::optional<response::StringType>> getClientMutationId(service::FieldParams&& params) const;

private:
	service::AwaitableResolver resolveTask(service::ResolverParams&& params);
	service::AwaitableResolver resolveClientMutationId(service::ResolverParams&& params);

	service::AwaitableResolver resolve_typename(service::ResolverParams&& params);
};

} // namespace graphql::today::object

#endif // COMPLETETASKPAYLOADOBJECT_H
