// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// WARNING! Do not edit this file manually, your changes will be overwritten.

#pragma once

#ifndef TODAY_APPOINTMENTCONNECTIONOBJECT_H
#define TODAY_APPOINTMENTCONNECTIONOBJECT_H

#include "TodaySchema.h"

namespace graphql::today::object {
namespace methods::AppointmentConnectionHas {

template <class TImpl>
concept getPageInfoWithParams = requires (TImpl impl, service::FieldParams params)
{
	{ service::AwaitableObject<std::shared_ptr<PageInfo>> { impl.getPageInfo(std::move(params)) } };
};

template <class TImpl>
concept getPageInfo = requires (TImpl impl)
{
	{ service::AwaitableObject<std::shared_ptr<PageInfo>> { impl.getPageInfo() } };
};

template <class TImpl>
concept getEdgesWithParams = requires (TImpl impl, service::FieldParams params)
{
	{ service::AwaitableObject<std::optional<std::vector<std::shared_ptr<AppointmentEdge>>>> { impl.getEdges(std::move(params)) } };
};

template <class TImpl>
concept getEdges = requires (TImpl impl)
{
	{ service::AwaitableObject<std::optional<std::vector<std::shared_ptr<AppointmentEdge>>>> { impl.getEdges() } };
};

template <class TImpl>
concept beginSelectionSet = requires (TImpl impl, const service::SelectionSetParams params)
{
	{ impl.beginSelectionSet(params) };
};

template <class TImpl>
concept endSelectionSet = requires (TImpl impl, const service::SelectionSetParams params)
{
	{ impl.endSelectionSet(params) };
};

} // namespace methods::AppointmentConnectionHas

class [[nodiscard("unnecessary construction")]] AppointmentConnection final
	: public service::Object
{
private:
	[[nodiscard("unnecessary call")]] service::AwaitableResolver resolvePageInfo(service::ResolverParams&& params) const;
	[[nodiscard("unnecessary call")]] service::AwaitableResolver resolveEdges(service::ResolverParams&& params) const;

	[[nodiscard("unnecessary call")]] service::AwaitableResolver resolve_typename(service::ResolverParams&& params) const;

	struct [[nodiscard("unnecessary construction")]] Concept
	{
		virtual ~Concept() = default;

		virtual void beginSelectionSet(const service::SelectionSetParams& params) const = 0;
		virtual void endSelectionSet(const service::SelectionSetParams& params) const = 0;

		[[nodiscard("unnecessary call")]] virtual service::AwaitableObject<std::shared_ptr<PageInfo>> getPageInfo(service::FieldParams&& params) const = 0;
		[[nodiscard("unnecessary call")]] virtual service::AwaitableObject<std::optional<std::vector<std::shared_ptr<AppointmentEdge>>>> getEdges(service::FieldParams&& params) const = 0;
	};

	template <class T>
	struct [[nodiscard("unnecessary construction")]] Model final
		: Concept
	{
		explicit Model(std::shared_ptr<T> pimpl) noexcept
			: _pimpl { std::move(pimpl) }
		{
		}

		[[nodiscard("unnecessary call")]] service::AwaitableObject<std::shared_ptr<PageInfo>> getPageInfo(service::FieldParams&& params) const override
		{
			if constexpr (methods::AppointmentConnectionHas::getPageInfoWithParams<T>)
			{
				return { _pimpl->getPageInfo(std::move(params)) };
			}
			else if constexpr (methods::AppointmentConnectionHas::getPageInfo<T>)
			{
				return { _pimpl->getPageInfo() };
			}
			else
			{
				throw service::unimplemented_method(R"ex(AppointmentConnection::getPageInfo)ex");
			}
		}

		[[nodiscard("unnecessary call")]] service::AwaitableObject<std::optional<std::vector<std::shared_ptr<AppointmentEdge>>>> getEdges(service::FieldParams&& params) const override
		{
			if constexpr (methods::AppointmentConnectionHas::getEdgesWithParams<T>)
			{
				return { _pimpl->getEdges(std::move(params)) };
			}
			else if constexpr (methods::AppointmentConnectionHas::getEdges<T>)
			{
				return { _pimpl->getEdges() };
			}
			else
			{
				throw service::unimplemented_method(R"ex(AppointmentConnection::getEdges)ex");
			}
		}

		void beginSelectionSet(const service::SelectionSetParams& params) const override
		{
			if constexpr (methods::AppointmentConnectionHas::beginSelectionSet<T>)
			{
				_pimpl->beginSelectionSet(params);
			}
		}

		void endSelectionSet(const service::SelectionSetParams& params) const override
		{
			if constexpr (methods::AppointmentConnectionHas::endSelectionSet<T>)
			{
				_pimpl->endSelectionSet(params);
			}
		}

	private:
		const std::shared_ptr<T> _pimpl;
	};

	explicit AppointmentConnection(std::unique_ptr<const Concept> pimpl) noexcept;

	[[nodiscard("unnecessary call")]] service::TypeNames getTypeNames() const noexcept;
	[[nodiscard("unnecessary call")]] service::ResolverMap getResolvers() const noexcept;

	void beginSelectionSet(const service::SelectionSetParams& params) const override;
	void endSelectionSet(const service::SelectionSetParams& params) const override;

	const std::unique_ptr<const Concept> _pimpl;

public:
	template <class T>
	explicit AppointmentConnection(std::shared_ptr<T> pimpl) noexcept
		: AppointmentConnection { std::unique_ptr<const Concept> { std::make_unique<Model<T>>(std::move(pimpl)) } }
	{
	}

	[[nodiscard("unnecessary call")]] static constexpr std::string_view getObjectType() noexcept
	{
		return { R"gql(AppointmentConnection)gql" };
	}
};

} // namespace graphql::today::object

#endif // TODAY_APPOINTMENTCONNECTIONOBJECT_H
