// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// WARNING! Do not edit this file manually, your changes will be overwritten.

#pragma once

#ifndef FOLDERCONNECTIONOBJECT_H
#define FOLDERCONNECTIONOBJECT_H

#include "TodaySchema.h"

namespace graphql::today::object {
namespace stub::FolderConnectionStubs {

template <class TImpl>
concept HasPageInfo = requires (TImpl impl, service::FieldParams params) 
{
	{ service::FieldResult<std::shared_ptr<PageInfo>> { impl.getPageInfo(std::move(params)) } };
};

template <class TImpl>
concept HasEdges = requires (TImpl impl, service::FieldParams params) 
{
	{ service::FieldResult<std::optional<std::vector<std::shared_ptr<FolderEdge>>>> { impl.getEdges(std::move(params)) } };
};

template <class TImpl>
concept HasBeginSelectionSet = requires (TImpl impl, const service::SelectionSetParams params) 
{
	{ impl.beginSelectionSet(params) };
};

template <class TImpl>
concept HasEndSelectionSet = requires (TImpl impl, const service::SelectionSetParams params) 
{
	{ impl.endSelectionSet(params) };
};

} // namespace stub::FolderConnectionStubs

class FolderConnection
	: public service::Object
{
private:
	service::AwaitableResolver resolvePageInfo(service::ResolverParams&& params);
	service::AwaitableResolver resolveEdges(service::ResolverParams&& params);

	service::AwaitableResolver resolve_typename(service::ResolverParams&& params);

	struct Concept
	{
		virtual ~Concept() = default;

		virtual void beginSelectionSet(const service::SelectionSetParams& params) const = 0;
		virtual void endSelectionSet(const service::SelectionSetParams& params) const = 0;

		virtual service::FieldResult<std::shared_ptr<PageInfo>> getPageInfo(service::FieldParams&& params) const = 0;
		virtual service::FieldResult<std::optional<std::vector<std::shared_ptr<FolderEdge>>>> getEdges(service::FieldParams&& params) const = 0;
	};

	template <class T>
	struct Model
		: Concept
	{
		Model(std::shared_ptr<T>&& pimpl) noexcept
			: _pimpl { std::move(pimpl) }
		{
		}

		void beginSelectionSet(const service::SelectionSetParams& params) const final
		{
			if constexpr (stub::FolderConnectionStubs::HasBeginSelectionSet<T>)
			{
				_pimpl->beginSelectionSet(params);
			}
		}

		void endSelectionSet(const service::SelectionSetParams& params) const final
		{
			if constexpr (stub::FolderConnectionStubs::HasEndSelectionSet<T>)
			{
				_pimpl->endSelectionSet(params);
			}
		}

		service::FieldResult<std::shared_ptr<PageInfo>> getPageInfo(service::FieldParams&& params) const final
		{
			if constexpr (stub::FolderConnectionStubs::HasPageInfo<T>)
			{
				return { _pimpl->getPageInfo(std::move(params)) };
			}
			else
			{
				throw std::runtime_error(R"ex(FolderConnection::getPageInfo is not implemented)ex");
			}
		}

		service::FieldResult<std::optional<std::vector<std::shared_ptr<FolderEdge>>>> getEdges(service::FieldParams&& params) const final
		{
			if constexpr (stub::FolderConnectionStubs::HasEdges<T>)
			{
				return { _pimpl->getEdges(std::move(params)) };
			}
			else
			{
				throw std::runtime_error(R"ex(FolderConnection::getEdges is not implemented)ex");
			}
		}

	private:
		const std::shared_ptr<T> _pimpl;
	};

	FolderConnection(std::unique_ptr<Concept>&& pimpl);

	void beginSelectionSet(const service::SelectionSetParams& params) const final;
	void endSelectionSet(const service::SelectionSetParams& params) const final;

	const std::unique_ptr<Concept> _pimpl;

public:
	template <class T>
	FolderConnection(std::shared_ptr<T> pimpl)
		: FolderConnection { std::unique_ptr<Concept> { std::make_unique<Model<T>>(std::move(pimpl)) } }
	{
	}
};

} // namespace graphql::today::object

#endif // FOLDERCONNECTIONOBJECT_H
