// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// WARNING! Do not edit this file manually, your changes will be overwritten.

module;

#include "HumanObject.h"

export module GraphQL.StarWars.HumanObject;

export namespace graphql::learn::object {

using object::Human;

} // namespace graphql::learn::object
