// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// WARNING! Do not edit this file manually, your changes will be overwritten.

module;

#include "SubscriptionObject.h"

export module GraphQL.StarWars.SubscriptionObject;

export namespace graphql::learn::object {

using object::Subscription;

} // namespace graphql::learn::object
